// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxbiHCs-gLlc-7J3ZF15vdj4OF-0t6Vmg',
    appId: '1:899491855193:web:7a506c77ff5b4cccaf6a48',
    messagingSenderId: '899491855193',
    projectId: 'chamba-9f6db',
    authDomain: 'chamba-9f6db.firebaseapp.com',
    storageBucket: 'chamba-9f6db.firebasestorage.app',
    measurementId: 'G-P94FM4T0VN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeUwMnmX-bpqmd3W8k57ttTaAmo_XocGs',
    appId: '1:899491855193:android:7dd6a185131eab5eaf6a48',
    messagingSenderId: '899491855193',
    projectId: 'chamba-9f6db',
    storageBucket: 'chamba-9f6db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmEXsGJAU-yTHDh5xJ1e7LEBk7shr_OsM',
    appId: '1:899491855193:ios:8d14ccd3462745c1af6a48',
    messagingSenderId: '899491855193',
    projectId: 'chamba-9f6db',
    storageBucket: 'chamba-9f6db.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmEXsGJAU-yTHDh5xJ1e7LEBk7shr_OsM',
    appId: '1:899491855193:ios:8d14ccd3462745c1af6a48',
    messagingSenderId: '899491855193',
    projectId: 'chamba-9f6db',
    storageBucket: 'chamba-9f6db.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxbiHCs-gLlc-7J3ZF15vdj4OF-0t6Vmg',
    appId: '1:899491855193:web:af9349a689556d96af6a48',
    messagingSenderId: '899491855193',
    projectId: 'chamba-9f6db',
    authDomain: 'chamba-9f6db.firebaseapp.com',
    storageBucket: 'chamba-9f6db.firebasestorage.app',
    measurementId: 'G-MHWL5HL8CG',
  );
}
